### ISSUE TITLE
docs: create tutorial for handbook page development

### ISSUE THREAD

**Issue by strixy16** [bhklab/handbook#7]
Make a tutorial for lab members to use to add pages to the handbook. Can present this at the beginning of any group development session and have it for them to refer back to 

Steps could include:

- Setting up local copy of repository
- Making a branch for their page 
- Some kind of Markdown overview OR how to get Markdown out of Google docs if that works
- Pushing the page to their specific branch
- Assigning a lab mate for code review

And then a section on how to do code review.

**Comment by strixy16** [comment]
I have a suggestion for this that I discovered in making the tutorial for page making.

If the first step for making a new page is making an issue, it gives you the opportunity to make a branch immediately associated with it. It's on the right side of the page under Development.

Once it's made, it prompts you to checkout the branch locally. 

This might simplify how that setup works for newer Git users, as opposed to using git checkout and such. Could be good to provide both alternatives

**Comment by jjjermiah** [comment]
closed by #23
