### ISSUE TITLE
GlobalProtect VPN

### ISSUE THREAD

**Issue by jjjermiah** [bhklab/handbook#72]
## Where
`onboarding_offboarding/Onboarding/vpn.md`

## Contents

Think about your experience trying to get on the VPN, think about a first year student trying to use this without any experience

- [ ] brief: What is the VPN for?
- [ ] this section can primarily just be links that you may have used to install the VPN
- [ ] we have a small guide at [https://bhklab.github.io/HPC4Health/setup/01_vpn_access/](https://bhklab.github.io/HPC4Health/setup/01_vpn_access/) which you can reorganize and/or copy+paste from 

## Resources
- [ ] [UHN VPN Doc](https://www.uhnresearch.ca/news/working-remotely-vpn)

**Comment by a2nabc** [comment]
Page finished - all contents added
