### ISSUE TITLE
change default port to something less common

### ISSUE THREAD

**Issue by jjjermiah** [bhklab/handbook#77]
**Describe the issue**
some users might already have port 8000 used for other software i.e printers

**Comment by mtran-code** [comment]
Issue can be circumvented by running `pixi run serve -a localhost:[DIFFERENT_PORT]` instead of `pixi run serve`.

**Comment by jjjermiah** [comment]
@mtran-code can i ask u to come up with something for this pls

**Comment by mtran-code** [comment]
mkdocs does not support nor plan to support randomizing/switching ports automatically based on availability. (see https://github.com/mkdocs/mkdocs/pull/3497)

Port notes:

- Full possible range of ports: 1024-49151, and 49152-65535 maybe.
- Common localhost ports used in dev: 3000, 3306, 4200, 5000, 7000, 8000, 8080, 9000, 27017
- (from https://stackoverflow.com/questions/46294415/developer-workflow-does-it-matter-which-port-is-used-during-development)

I figure using 8001 works and is most likely unused on everyone's local machine. The alternative is to hack a script to check for the available ports and use what's free.
